#spring:
#  application:
#    name: AuthenticationService
#server:
#  port: 8089
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://172.23.239.227:8761/eureka
#    register-with-eureka: true
#
#info:
#  app:
#    description: Authentication Service is up and has no problem
#    name: Authentication Service
#    version: 1.0.0