#eureka:
#  client:
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://172.23.239.227:8061/eureka
#info:
#  app:
#    description: User Service is up and has no problem
#    name: User Service
#    version: 1.0.0
#
#
#  
#spring:
#  application:
#    name: User-Service
#  data:
#   mongodb:
#     database: UserServiceDb
#     host: localhost
#     password: root12
#     port: 27017
#     username: root12
#  profiles:
#    active: Development
#  cloud:
#    config:
#      uri: http://172.23.239.212:8083
#server:
#  port: 8085
#
#spring:
#  data:
#    mongodb:
#        database: UserServiceDb
#        host: localhost
#        password: root12
#        port: 27017
#        username: root12
