#server:
#  port: 8070
#
#eureka:
#  client:
#    register-with-eureka: true
#    serviceUrl:
#      defaultZone: http://172.23.239.227:8061/eureka
#
#info:
#  app:
#    description: Search Service is up and has no problem
#    name: Search Service
#    version: 1.0.0
#
#spring:
#  application:
#    name: Search-Service
#  profiles:
#    active: Development
#  cloud:
#    config:
#      uri: http://172.23.239.212:8062
#
